# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  RaylibTest_config = debug_x64
  ImGui_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  RaylibTest_config = debug_x86
  ImGui_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  RaylibTest_config = debug_arm64
  ImGui_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  RaylibTest_config = release_x64
  ImGui_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  RaylibTest_config = release_x86
  ImGui_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  RaylibTest_config = release_arm64
  ImGui_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib RaylibTest ImGui

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib: ImGui
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C raylib-master -f Makefile config=$(raylib_config)
endif

RaylibTest: raylib 
ifneq (,$(RaylibTest_config))
	@echo "==== Building RaylibTest ($(RaylibTest_config)) ===="
	@${MAKE} --no-print-directory -C game -f Makefile config=$(RaylibTest_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building rlImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C build -f ImGui.make config=$(ImGui_config)
endif
clean:
	@${MAKE} --no-print-directory -C raylib-master -f Makefile clean
	@${MAKE} --no-print-directory -C game -f Makefile clean
	@${MAKE} --no-print-directory -C build -f ImGui.make clean
help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   RaylibTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"